### ISSUE TITLE
Apache homepage stays in 404 even if the asf-site branch is configured and published

### ISSUE THREAD

**Issue by tisonkun** [apache/apache-website-template#15]
See also https://github.com/apache/incubator-kvrocks-website/tree/asf-site.

It seems `.asf.yaml` is correctly configured and all static site staff are published, but still https://kvrocks.apache.org/ returns 404 NOT FOUND.

I don't have an idea about how to resolve the issue and throw the question here - how to make homepage hosted properly?

**Comment by mik-laj** [comment]
Can you ask on INFRA jira?
https://issues.apache.org/jira/projects/INFRA/issues/INFRA-22097?filter=allopenissues

**Comment by tisonkun** [comment]
Thanks for your reply. It turn out that because of deploying takes some time.

Closed as invalid.
