### ISSUE TITLE
Update docusaurus template to use latest stable version 3.6.3

### ISSUE THREAD

**Issue by lhotari** [apache/apache-website-template#20]
It would be useful to start using the latest stable version of docusaurus from the beginning:
https://github.com/apache/apache-website-template/blob/f8129ca66fdff1c97e0749eb2ed319f1739f6f34/package.json#L18-L19
/cc @tisonkun 

A new feature in docusaurus 3.6 is the use of Rspack which is a lot faster than webpack:
https://docusaurus.io/blog/releases/3.6#docusaurus-faster
It's necessary to opt-in to use Rspack.

**Comment by tisonkun** [comment]
Cool. Let me take a look :D

Thank you!

**Comment by lhotari** [comment]
Thank you @tisonkun. I'll provide feedback about the template if we happen to use this in the Apache Hunter (incubating) project, discussion thread https://lists.apache.org/thread/5nzsjwfwp7ssvo7d9kcl7gjw6d4bhrdo .
